name = "glance_printer"
version = "0.1.0"
description = "A pretty_printer for the glance AST"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
repository = { type = "github", user = "bcpeinhardt", repo = "glance_printer" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.30"
glance = "~> 0.6"
glam = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 0.10"
simplifile = "~> 0.1"
testbldr = "~> 0.1"
gap = "~> 0.7"
